# Generated by Django 2.1.7 on 2020-04-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200408_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_active',
            field=models.IntegerField(default='2'),
        ),
    ]
