# Generated by Django 2.1.7 on 2020-04-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_signup_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='is_active',
            new_name='isActive',
        ),
    ]
